### ISSUE TITLE
Add styles to our todo application. 

### ISSUE THREAD

**Issue by imkaka** [imkaka/todo#1]

**Comment by MohdImran001** [comment]
Hii @imkaka, I'd love to work on this. Do you have any suggestions on the design like what library to use or what color theme to use?

**Comment by imkaka** [comment]
Hi @MohdImran001 

We want to replicate something kind of this page 1 and page 3 but for web, with it being responsive. 


https://file.mockplus.com/image/2019/07/acd2fb53-5e6f-4308-b97e-3e2ed823d773.jpg

You can use any lib like bootstrap Or material UI Or just plain css will also do. 

It's a learning process in the end 😇

**Comment by MohdImran001** [comment]
Thats great. I will start it. I might be a little slow because of my classes but I will keep you updated.

**Comment by MohdImran001** [comment]
Hey @imkaka, It would of great help, If you could divide this issue into two different issues both with Hactoberfest label. One for page 1 styles and second for page 3 styles.

**Comment by imkaka** [comment]
@MohdImran001 you can raise two different PRs for two different pages. :D

**Comment by MohdImran001** [comment]
> Hi @MohdImran001
> 
> We want to replicate something kind of this page 1 and page 3 but for web, with it being responsive.
> 
> https://file.mockplus.com/image/2019/07/acd2fb53-5e6f-4308-b97e-3e2ed823d773.jpg
> 
> You can use any lib like bootstrap Or material UI Or just plain css will also do.
> 
> It's a learning process in the end 😇

Hey @imkaka, can you share the color codes used in this design

**Comment by imkaka** [comment]
Hey @MohdImran001 you can use any similar color code, no restrictions.

**Comment by zuhairnaqi** [comment]
Hi @imkaka I'm working on it.

**Comment by imkaka** [comment]
Hey @zuhairnaqi 

@MohdImran001 is working on this, let's wait for his status till tomorrow. 

Till then you can pick other issue, adding routing to our to do app.

**Comment by zuhairnaqi** [comment]
OK

**Comment by MohdImran001** [comment]
Hi @imkaka and @zuhairnaqi. I am really sorry I couldn't complete it. @zuhairnaqi You can work on it.

**Comment by zuhairnaqi** [comment]
ok @imkaka kindly assign issue to me, I'll do it as possible as I can.
